name=LogosRoboticsSDK
version=0.0.1
author=Prele Prelevic
maintainer=Prele Prelevic
sentence=Open source robotics SDK for embedded motion control.
paragraph=Hardware independent robotics SDK supporting multiple kinematics and platforms.
category=Device Control
architectures=*